# This is a basic workflow to help you get started with Actions

name: Google Hangout Integration

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Google Chat Notification
      run: |
          curl -L --request POST '${{ secrets.WEBHOOK }}' \
          -H 'Content-Type: application/json' \
          --data-raw '{"project":"MySaas","group":"Payments","event":"Payment received","description":"YourDescription","notify":true}'
