# This is a basic workflow to help you get started with Actions

name: Google Hangout Integration

# Controls when the workflow will run
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Google Chat Notification
      id: google-chat
      run: |
          curl -L --request POST '${{ secrets.WEBHOOK }}' \
          -H 'Content-Type: application/json' \
          --data-raw '{
              "text": "${{job.status}}: Job , ${{ github.event.repository.name }}///${{github.ref}} [${{github.run_number}}]\n More info at: (${{ steps.google-chat.outputs.url_output }})"
          }'
